/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HealthcareRegistrationProver } from "./HealthcareRegistrationProver";
export * as factories from "./factories";
export { HealthcareRegistrationProver__factory } from "./factories/HealthcareRegistrationProver__factory";
