/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type SealStruct = {
  verifierSelector: BytesLike;
  seal: BytesLike[];
  mode: BigNumberish;
};

export type SealStructOutput = [
  verifierSelector: string,
  seal: string[],
  mode: bigint
] & { verifierSelector: string; seal: string[]; mode: bigint };

export type CallAssumptionsStruct = {
  proverContractAddress: AddressLike;
  functionSelector: BytesLike;
  settleChainId: BigNumberish;
  settleBlockNumber: BigNumberish;
  settleBlockHash: BytesLike;
};

export type CallAssumptionsStructOutput = [
  proverContractAddress: string,
  functionSelector: string,
  settleChainId: bigint,
  settleBlockNumber: bigint,
  settleBlockHash: string
] & {
  proverContractAddress: string;
  functionSelector: string;
  settleChainId: bigint;
  settleBlockNumber: bigint;
  settleBlockHash: string;
};

export type ProofStruct = {
  seal: SealStruct;
  callGuestId: BytesLike;
  length: BigNumberish;
  callAssumptions: CallAssumptionsStruct;
};

export type ProofStructOutput = [
  seal: SealStructOutput,
  callGuestId: string,
  length: bigint,
  callAssumptions: CallAssumptionsStructOutput
] & {
  seal: SealStructOutput;
  callGuestId: string;
  length: bigint;
  callAssumptions: CallAssumptionsStructOutput;
};

export declare namespace HealthcareRegistration {
  export type BaseRequestStruct = {
    requester: AddressLike;
    requestType: BigNumberish;
    status: BigNumberish;
    requestTime: BigNumberish;
    processedBy: AddressLike;
    processedTime: BigNumberish;
  };

  export type BaseRequestStructOutput = [
    requester: string,
    requestType: bigint,
    status: bigint,
    requestTime: bigint,
    processedBy: string,
    processedTime: bigint
  ] & {
    requester: string;
    requestType: bigint;
    status: bigint;
    requestTime: bigint;
    processedBy: string;
    processedTime: bigint;
  };

  export type AdminAccessRequestStruct = {
    base: HealthcareRegistration.BaseRequestStruct;
    adminRole: BigNumberish;
    reason: string;
  };

  export type AdminAccessRequestStructOutput = [
    base: HealthcareRegistration.BaseRequestStructOutput,
    adminRole: bigint,
    reason: string
  ] & {
    base: HealthcareRegistration.BaseRequestStructOutput;
    adminRole: bigint;
    reason: string;
  };

  export type BaseRecordStruct = {
    walletAddress: AddressLike;
    emailHash: BytesLike;
    registrationTime: BigNumberish;
    isActive: boolean;
    requestId: BigNumberish;
  };

  export type BaseRecordStructOutput = [
    walletAddress: string,
    emailHash: string,
    registrationTime: bigint,
    isActive: boolean,
    requestId: bigint
  ] & {
    walletAddress: string;
    emailHash: string;
    registrationTime: bigint;
    isActive: boolean;
    requestId: bigint;
  };

  export type OrganizationRecordStruct = {
    base: HealthcareRegistration.BaseRecordStruct;
    orgType: BigNumberish;
    domain: string;
    organizationName: string;
  };

  export type OrganizationRecordStructOutput = [
    base: HealthcareRegistration.BaseRecordStructOutput,
    orgType: bigint,
    domain: string,
    organizationName: string
  ] & {
    base: HealthcareRegistration.BaseRecordStructOutput;
    orgType: bigint;
    domain: string;
    organizationName: string;
  };

  export type OrganizationRegistrationRequestStruct = {
    base: HealthcareRegistration.BaseRequestStruct;
    orgType: BigNumberish;
    domain: string;
    organizationName: string;
    emailHash: BytesLike;
  };

  export type OrganizationRegistrationRequestStructOutput = [
    base: HealthcareRegistration.BaseRequestStructOutput,
    orgType: bigint,
    domain: string,
    organizationName: string,
    emailHash: string
  ] & {
    base: HealthcareRegistration.BaseRequestStructOutput;
    orgType: bigint;
    domain: string;
    organizationName: string;
    emailHash: string;
  };

  export type PatientRecordStruct = {
    base: HealthcareRegistration.BaseRecordStruct;
  };

  export type PatientRecordStructOutput = [
    base: HealthcareRegistration.BaseRecordStructOutput
  ] & { base: HealthcareRegistration.BaseRecordStructOutput };

  export type PatientRegistrationRequestStruct = {
    base: HealthcareRegistration.BaseRequestStruct;
    emailHash: BytesLike;
  };

  export type PatientRegistrationRequestStructOutput = [
    base: HealthcareRegistration.BaseRequestStructOutput,
    emailHash: string
  ] & {
    base: HealthcareRegistration.BaseRequestStructOutput;
    emailHash: string;
  };
}

export declare namespace HealthcareRegistrationProver {
  export type RegistrationDataStruct = {
    requestedRole: BigNumberish;
    walletAddress: AddressLike;
    domain: string;
    organizationName: string;
    emailHash: BytesLike;
  };

  export type RegistrationDataStructOutput = [
    requestedRole: bigint,
    walletAddress: string,
    domain: string,
    organizationName: string,
    emailHash: string
  ] & {
    requestedRole: bigint;
    walletAddress: string;
    domain: string;
    organizationName: string;
    emailHash: string;
  };
}

export interface HealthcareRegistrationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_setTestVerifier"
      | "addAdmin"
      | "adminRequests"
      | "admins"
      | "approveRequest"
      | "deactivateUser"
      | "domainToUser"
      | "emailDomainProver"
      | "getAdminRequest"
      | "getAdminType"
      | "getDomainOwner"
      | "getOrganizationRecord"
      | "getOrganizationRequest"
      | "getPatientRecord"
      | "getPatientRequest"
      | "getPendingRequests"
      | "getPendingRequestsByType"
      | "getRegistrationStats"
      | "getRequestBase"
      | "getUserType"
      | "isDomainTaken"
      | "isUserRegistered"
      | "organizationRecords"
      | "organizationRequests"
      | "owner"
      | "patientRecords"
      | "patientRequests"
      | "pendingRequestCount"
      | "registerHospital"
      | "registerInsurer"
      | "registerPatient"
      | "rejectRequest"
      | "renounceOwnership"
      | "requestAdminAccess"
      | "requestCount"
      | "requests"
      | "totalHospitals"
      | "totalInsurers"
      | "totalPatients"
      | "totalRegisteredUsers"
      | "transferOwnership"
      | "updateAdminPermissions"
      | "usedEmailHashes"
      | "userToRequestId"
      | "userTypes"
      | "validateHospitalDomain"
      | "validateInsurerDomain"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAdded"
      | "HospitalRegistered"
      | "InsurerRegistered"
      | "OwnershipTransferred"
      | "PatientRegistered"
      | "RequestApproved"
      | "RequestRejected"
      | "RequestSubmitted"
      | "UserDeactivated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "_setTestVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admins", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "approveRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "domainToUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "emailDomainProver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminType",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrganizationRecord",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrganizationRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientRecord",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequestsByType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrationStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestBase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserType",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDomainTaken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "organizationRecords",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "organizationRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "patientRecords",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "patientRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerHospital",
    values: [ProofStruct, HealthcareRegistrationProver.RegistrationDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "registerInsurer",
    values: [ProofStruct, HealthcareRegistrationProver.RegistrationDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPatient",
    values: [ProofStruct, HealthcareRegistrationProver.RegistrationDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectRequest",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAdminAccess",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalHospitals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalInsurers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPatients",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRegisteredUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAdminPermissions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usedEmailHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userToRequestId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTypes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateHospitalDomain",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validateInsurerDomain",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "_setTestVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "domainToUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emailDomainProver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdminRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdminType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrganizationRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrganizationRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequestsByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrationStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDomainTaken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "organizationRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "organizationRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "patientRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerHospital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerInsurer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAdminAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalHospitals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalInsurers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRegisteredUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAdminPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedEmailHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userToRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userTypes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateHospitalDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateInsurerDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace AdminAddedEvent {
  export type InputTuple = [admin: AddressLike, role: BigNumberish];
  export type OutputTuple = [admin: string, role: bigint];
  export interface OutputObject {
    admin: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HospitalRegisteredEvent {
  export type InputTuple = [
    hospital: AddressLike,
    domain: string,
    emailHash: BytesLike
  ];
  export type OutputTuple = [
    hospital: string,
    domain: string,
    emailHash: string
  ];
  export interface OutputObject {
    hospital: string;
    domain: string;
    emailHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InsurerRegisteredEvent {
  export type InputTuple = [
    insurer: AddressLike,
    domain: string,
    emailHash: BytesLike
  ];
  export type OutputTuple = [
    insurer: string,
    domain: string,
    emailHash: string
  ];
  export interface OutputObject {
    insurer: string;
    domain: string;
    emailHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientRegisteredEvent {
  export type InputTuple = [patient: AddressLike];
  export type OutputTuple = [patient: string];
  export interface OutputObject {
    patient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestApprovedEvent {
  export type InputTuple = [requestId: BigNumberish, approver: AddressLike];
  export type OutputTuple = [requestId: bigint, approver: string];
  export interface OutputObject {
    requestId: bigint;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestRejectedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    rejecter: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    requestId: bigint,
    rejecter: string,
    reason: string
  ];
  export interface OutputObject {
    requestId: bigint;
    rejecter: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestSubmittedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    requestType: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    requestType: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    requestType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserDeactivatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthcareRegistration extends BaseContract {
  connect(runner?: ContractRunner | null): HealthcareRegistration;
  waitForDeployment(): Promise<this>;

  interface: HealthcareRegistrationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _setTestVerifier: TypedContractMethod<
    [newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  addAdmin: TypedContractMethod<
    [newAdmin: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [HealthcareRegistration.BaseRequestStructOutput, bigint, string] & {
        base: HealthcareRegistration.BaseRequestStructOutput;
        adminRole: bigint;
        reason: string;
      }
    ],
    "view"
  >;

  admins: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint] & {
        isActive: boolean;
        role: bigint;
        permissions: bigint;
        adminSince: bigint;
      }
    ],
    "view"
  >;

  approveRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deactivateUser: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  domainToUser: TypedContractMethod<[arg0: string], [string], "view">;

  emailDomainProver: TypedContractMethod<[], [string], "view">;

  getAdminRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [HealthcareRegistration.AdminAccessRequestStructOutput],
    "view"
  >;

  getAdminType: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getDomainOwner: TypedContractMethod<[domain: string], [string], "view">;

  getOrganizationRecord: TypedContractMethod<
    [organization: AddressLike],
    [HealthcareRegistration.OrganizationRecordStructOutput],
    "view"
  >;

  getOrganizationRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [HealthcareRegistration.OrganizationRegistrationRequestStructOutput],
    "view"
  >;

  getPatientRecord: TypedContractMethod<
    [patient: AddressLike],
    [HealthcareRegistration.PatientRecordStructOutput],
    "view"
  >;

  getPatientRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [HealthcareRegistration.PatientRegistrationRequestStructOutput],
    "view"
  >;

  getPendingRequests: TypedContractMethod<[], [bigint[]], "view">;

  getPendingRequestsByType: TypedContractMethod<
    [reqType: BigNumberish],
    [bigint[]],
    "view"
  >;

  getRegistrationStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalUsers: bigint;
        patients: bigint;
        hospitals: bigint;
        insurers: bigint;
      }
    ],
    "view"
  >;

  getRequestBase: TypedContractMethod<
    [requestId: BigNumberish],
    [HealthcareRegistration.BaseRequestStructOutput],
    "view"
  >;

  getUserType: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  isDomainTaken: TypedContractMethod<[domain: string], [boolean], "view">;

  isUserRegistered: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  organizationRecords: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        HealthcareRegistration.BaseRecordStructOutput,
        bigint,
        string,
        string
      ] & {
        base: HealthcareRegistration.BaseRecordStructOutput;
        orgType: bigint;
        domain: string;
        organizationName: string;
      }
    ],
    "view"
  >;

  organizationRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        HealthcareRegistration.BaseRequestStructOutput,
        bigint,
        string,
        string,
        string
      ] & {
        base: HealthcareRegistration.BaseRequestStructOutput;
        orgType: bigint;
        domain: string;
        organizationName: string;
        emailHash: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  patientRecords: TypedContractMethod<
    [arg0: AddressLike],
    [HealthcareRegistration.BaseRecordStructOutput],
    "view"
  >;

  patientRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [HealthcareRegistration.BaseRequestStructOutput, string] & {
        base: HealthcareRegistration.BaseRequestStructOutput;
        emailHash: string;
      }
    ],
    "view"
  >;

  pendingRequestCount: TypedContractMethod<[], [bigint], "view">;

  registerHospital: TypedContractMethod<
    [
      arg0: ProofStruct,
      registrationData: HealthcareRegistrationProver.RegistrationDataStruct
    ],
    [void],
    "nonpayable"
  >;

  registerInsurer: TypedContractMethod<
    [
      arg0: ProofStruct,
      registrationData: HealthcareRegistrationProver.RegistrationDataStruct
    ],
    [void],
    "nonpayable"
  >;

  registerPatient: TypedContractMethod<
    [
      arg0: ProofStruct,
      registrationData: HealthcareRegistrationProver.RegistrationDataStruct
    ],
    [void],
    "nonpayable"
  >;

  rejectRequest: TypedContractMethod<
    [requestId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestAdminAccess: TypedContractMethod<
    [requestedRole: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  requestCount: TypedContractMethod<[], [bigint], "view">;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, bigint] & {
        requester: string;
        requestType: bigint;
        status: bigint;
        requestTime: bigint;
        processedBy: string;
        processedTime: bigint;
      }
    ],
    "view"
  >;

  totalHospitals: TypedContractMethod<[], [bigint], "view">;

  totalInsurers: TypedContractMethod<[], [bigint], "view">;

  totalPatients: TypedContractMethod<[], [bigint], "view">;

  totalRegisteredUsers: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAdminPermissions: TypedContractMethod<
    [admin: AddressLike, permissions: BigNumberish],
    [void],
    "nonpayable"
  >;

  usedEmailHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  userToRequestId: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userTypes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  validateHospitalDomain: TypedContractMethod<
    [domain: string],
    [boolean],
    "view"
  >;

  validateInsurerDomain: TypedContractMethod<
    [domain: string],
    [boolean],
    "view"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_setTestVerifier"
  ): TypedContractMethod<[newVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<
    [newAdmin: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adminRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [HealthcareRegistration.BaseRequestStructOutput, bigint, string] & {
        base: HealthcareRegistration.BaseRequestStructOutput;
        adminRole: bigint;
        reason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint] & {
        isActive: boolean;
        role: bigint;
        permissions: bigint;
        adminSince: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approveRequest"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateUser"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "domainToUser"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "emailDomainProver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAdminRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [HealthcareRegistration.AdminAccessRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAdminType"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDomainOwner"
  ): TypedContractMethod<[domain: string], [string], "view">;
  getFunction(
    nameOrSignature: "getOrganizationRecord"
  ): TypedContractMethod<
    [organization: AddressLike],
    [HealthcareRegistration.OrganizationRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrganizationRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [HealthcareRegistration.OrganizationRegistrationRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPatientRecord"
  ): TypedContractMethod<
    [patient: AddressLike],
    [HealthcareRegistration.PatientRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPatientRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [HealthcareRegistration.PatientRegistrationRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingRequests"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPendingRequestsByType"
  ): TypedContractMethod<[reqType: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRegistrationStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalUsers: bigint;
        patients: bigint;
        hospitals: bigint;
        insurers: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequestBase"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [HealthcareRegistration.BaseRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserType"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isDomainTaken"
  ): TypedContractMethod<[domain: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isUserRegistered"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "organizationRecords"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        HealthcareRegistration.BaseRecordStructOutput,
        bigint,
        string,
        string
      ] & {
        base: HealthcareRegistration.BaseRecordStructOutput;
        orgType: bigint;
        domain: string;
        organizationName: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "organizationRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        HealthcareRegistration.BaseRequestStructOutput,
        bigint,
        string,
        string,
        string
      ] & {
        base: HealthcareRegistration.BaseRequestStructOutput;
        orgType: bigint;
        domain: string;
        organizationName: string;
        emailHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "patientRecords"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [HealthcareRegistration.BaseRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "patientRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [HealthcareRegistration.BaseRequestStructOutput, string] & {
        base: HealthcareRegistration.BaseRequestStructOutput;
        emailHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerHospital"
  ): TypedContractMethod<
    [
      arg0: ProofStruct,
      registrationData: HealthcareRegistrationProver.RegistrationDataStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerInsurer"
  ): TypedContractMethod<
    [
      arg0: ProofStruct,
      registrationData: HealthcareRegistrationProver.RegistrationDataStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerPatient"
  ): TypedContractMethod<
    [
      arg0: ProofStruct,
      registrationData: HealthcareRegistrationProver.RegistrationDataStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestAdminAccess"
  ): TypedContractMethod<
    [requestedRole: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, bigint] & {
        requester: string;
        requestType: bigint;
        status: bigint;
        requestTime: bigint;
        processedBy: string;
        processedTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalHospitals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalInsurers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPatients"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRegisteredUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAdminPermissions"
  ): TypedContractMethod<
    [admin: AddressLike, permissions: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usedEmailHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "userToRequestId"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTypes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "validateHospitalDomain"
  ): TypedContractMethod<[domain: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "validateInsurerDomain"
  ): TypedContractMethod<[domain: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "HospitalRegistered"
  ): TypedContractEvent<
    HospitalRegisteredEvent.InputTuple,
    HospitalRegisteredEvent.OutputTuple,
    HospitalRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InsurerRegistered"
  ): TypedContractEvent<
    InsurerRegisteredEvent.InputTuple,
    InsurerRegisteredEvent.OutputTuple,
    InsurerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PatientRegistered"
  ): TypedContractEvent<
    PatientRegisteredEvent.InputTuple,
    PatientRegisteredEvent.OutputTuple,
    PatientRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RequestApproved"
  ): TypedContractEvent<
    RequestApprovedEvent.InputTuple,
    RequestApprovedEvent.OutputTuple,
    RequestApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RequestRejected"
  ): TypedContractEvent<
    RequestRejectedEvent.InputTuple,
    RequestRejectedEvent.OutputTuple,
    RequestRejectedEvent.OutputObject
  >;
  getEvent(
    key: "RequestSubmitted"
  ): TypedContractEvent<
    RequestSubmittedEvent.InputTuple,
    RequestSubmittedEvent.OutputTuple,
    RequestSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "UserDeactivated"
  ): TypedContractEvent<
    UserDeactivatedEvent.InputTuple,
    UserDeactivatedEvent.OutputTuple,
    UserDeactivatedEvent.OutputObject
  >;

  filters: {
    "AdminAdded(address,uint8)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "HospitalRegistered(address,string,bytes32)": TypedContractEvent<
      HospitalRegisteredEvent.InputTuple,
      HospitalRegisteredEvent.OutputTuple,
      HospitalRegisteredEvent.OutputObject
    >;
    HospitalRegistered: TypedContractEvent<
      HospitalRegisteredEvent.InputTuple,
      HospitalRegisteredEvent.OutputTuple,
      HospitalRegisteredEvent.OutputObject
    >;

    "InsurerRegistered(address,string,bytes32)": TypedContractEvent<
      InsurerRegisteredEvent.InputTuple,
      InsurerRegisteredEvent.OutputTuple,
      InsurerRegisteredEvent.OutputObject
    >;
    InsurerRegistered: TypedContractEvent<
      InsurerRegisteredEvent.InputTuple,
      InsurerRegisteredEvent.OutputTuple,
      InsurerRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PatientRegistered(address)": TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;
    PatientRegistered: TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;

    "RequestApproved(uint256,address)": TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;
    RequestApproved: TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;

    "RequestRejected(uint256,address,string)": TypedContractEvent<
      RequestRejectedEvent.InputTuple,
      RequestRejectedEvent.OutputTuple,
      RequestRejectedEvent.OutputObject
    >;
    RequestRejected: TypedContractEvent<
      RequestRejectedEvent.InputTuple,
      RequestRejectedEvent.OutputTuple,
      RequestRejectedEvent.OutputObject
    >;

    "RequestSubmitted(uint256,address,uint8)": TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;
    RequestSubmitted: TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;

    "UserDeactivated(address)": TypedContractEvent<
      UserDeactivatedEvent.InputTuple,
      UserDeactivatedEvent.OutputTuple,
      UserDeactivatedEvent.OutputObject
    >;
    UserDeactivated: TypedContractEvent<
      UserDeactivatedEvent.InputTuple,
      UserDeactivatedEvent.OutputTuple,
      UserDeactivatedEvent.OutputObject
    >;
  };
}
