include:
  # chain
  - anvil/service.yaml
  # vlayer
  - vdns_server/service.yaml
  - call_server/service.yaml
  # webproofs 
  - websockify/service.yaml
  - websockify-test-client/service.yaml
  - notary-server/service.yaml

networks:
  zkmed-network: # Renamed from vlayer-network
    name: zkmed-network # Renamed from vlayer-network
    driver: bridge

