/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GreetingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getGreeting"
      | "getMyGreeting"
      | "getMyGreetingCount"
      | "getUserGreeting"
      | "getUserGreetingCount"
      | "greetingCounts"
      | "owner"
      | "setGreeting"
      | "totalGreetings"
      | "userGreetings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GreetingSet" | "GreetingUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getGreeting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyGreeting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyGreetingCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserGreeting",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserGreetingCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "greetingCounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "setGreeting", values: [string]): string;
  encodeFunctionData(
    functionFragment: "totalGreetings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userGreetings",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getGreeting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyGreeting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyGreetingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserGreeting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserGreetingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "greetingCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGreeting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalGreetings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userGreetings",
    data: BytesLike
  ): Result;
}

export namespace GreetingSetEvent {
  export type InputTuple = [user: AddressLike, newGreeting: string];
  export type OutputTuple = [user: string, newGreeting: string];
  export interface OutputObject {
    user: string;
    newGreeting: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GreetingUpdatedEvent {
  export type InputTuple = [oldGreeting: string, newGreeting: string];
  export type OutputTuple = [oldGreeting: string, newGreeting: string];
  export interface OutputObject {
    oldGreeting: string;
    newGreeting: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Greeting extends BaseContract {
  connect(runner?: ContractRunner | null): Greeting;
  waitForDeployment(): Promise<this>;

  interface: GreetingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getGreeting: TypedContractMethod<[], [string], "view">;

  getMyGreeting: TypedContractMethod<[], [string], "view">;

  getMyGreetingCount: TypedContractMethod<[], [bigint], "view">;

  getUserGreeting: TypedContractMethod<[user: AddressLike], [string], "view">;

  getUserGreetingCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  greetingCounts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setGreeting: TypedContractMethod<[_greeting: string], [void], "nonpayable">;

  totalGreetings: TypedContractMethod<[], [bigint], "view">;

  userGreetings: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getGreeting"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyGreeting"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyGreetingCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserGreeting"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserGreetingCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "greetingCounts"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setGreeting"
  ): TypedContractMethod<[_greeting: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalGreetings"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userGreetings"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "GreetingSet"
  ): TypedContractEvent<
    GreetingSetEvent.InputTuple,
    GreetingSetEvent.OutputTuple,
    GreetingSetEvent.OutputObject
  >;
  getEvent(
    key: "GreetingUpdated"
  ): TypedContractEvent<
    GreetingUpdatedEvent.InputTuple,
    GreetingUpdatedEvent.OutputTuple,
    GreetingUpdatedEvent.OutputObject
  >;

  filters: {
    "GreetingSet(address,string)": TypedContractEvent<
      GreetingSetEvent.InputTuple,
      GreetingSetEvent.OutputTuple,
      GreetingSetEvent.OutputObject
    >;
    GreetingSet: TypedContractEvent<
      GreetingSetEvent.InputTuple,
      GreetingSetEvent.OutputTuple,
      GreetingSetEvent.OutputObject
    >;

    "GreetingUpdated(string,string)": TypedContractEvent<
      GreetingUpdatedEvent.InputTuple,
      GreetingUpdatedEvent.OutputTuple,
      GreetingUpdatedEvent.OutputObject
    >;
    GreetingUpdated: TypedContractEvent<
      GreetingUpdatedEvent.InputTuple,
      GreetingUpdatedEvent.OutputTuple,
      GreetingUpdatedEvent.OutputObject
    >;
  };
}
