services:
  anvil-l2-mantle:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-l2-mantle
    platform: linux/amd64
    command: ["anvil --host 0.0.0.0 --chain-id 31337"]
    ports:
      - "127.0.0.1:8545:8545"
    networks:
      - zkmed-network