// zkMed Contract Types - Centralized exports
// Generated by TypeChain from Foundry contract artifacts

// Healthcare Registration Contract
export * as HealthcareRegistrationTypes from './HealthcareRegistration/index';
export { HealthcareRegistration__factory } from './HealthcareRegistration/factories/HealthcareRegistration__factory';

// Healthcare Registration Prover Contract  
export * as HealthcareRegistrationProverTypes from './HealthcareRegistrationProver/index';
export { HealthcareRegistrationProver__factory } from './HealthcareRegistrationProver/factories/HealthcareRegistrationProver__factory';

// Contract configuration utilities
export {
  fetchContractAddresses,
  getHealthcareRegistrationContractAddress,
  getHealthcareRegistrationProverContractAddress,
  getContractStatus,
  clearContractCache,
  type ContractsResponse,
  type ContractInfo
} from '../../configs/contract-config';

// Contract types for easier imports
export type HealthcareRegistrationContract = import('./HealthcareRegistration/HealthcareRegistration').HealthcareRegistration;
export type HealthcareRegistrationProverContract = import('./HealthcareRegistrationProver/HealthcareRegistrationProver').HealthcareRegistrationProver;

// Common contract interaction patterns
export interface ContractConfig {
  address: string;
  chainId: number;
  rpcUrl: string;
}

export interface zkMedContracts {
  healthcareRegistration: ContractConfig;
  healthcareRegistrationProver: ContractConfig;
}
