/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HealthcareRegistration } from "./HealthcareRegistration";
export * as factories from "./factories";
export { HealthcareRegistration__factory } from "./factories/HealthcareRegistration__factory";
